[program:infraswe-communication-bulk]
environment=PROC_NAME="%(program_name)s"
command=/opt/supervisor-scripts/infraswe-communication-bulk.sh
directory=/workspace/infraswe
autostart=true
autorestart=unexpected
startsecs=5
startretries=3
stopsignal=TERM
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
redirect_stderr=true
stdout_logfile_maxbytes=0
